site_name: "Climate and Disaster Resilience Pilot"
theme:
  name: material

nav:
  - Home: index.md
  - Objectives: objectives.md
  - Datasets: datasets.md
  - Methodology: methodology.md
  - Demo: demo.md
  - Future Directions: future_directions.md

theme:
  name: material
  custom_dir: docs/overrides

markdown_extensions:
  - attr_list

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/geolabs/cdrp-d100-geolabs
